// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/general": {
    params: {};
  };
  "/data-display": {
    params: {};
  };
  "/form": {
    params: {};
  };
  "/feedback": {
    params: {};
  };
  "/overlay": {
    params: {};
  };
  "/navigation": {
    params: {};
  };
  "/commerce": {
    params: {};
  };
  "/utils": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/general" | "/data-display" | "/form" | "/feedback" | "/overlay" | "/navigation" | "/commerce" | "/utils";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/general.tsx": {
    id: "routes/general";
    page: "/general";
  };
  "routes/data-display.tsx": {
    id: "routes/data-display";
    page: "/data-display";
  };
  "routes/form.tsx": {
    id: "routes/form";
    page: "/form";
  };
  "routes/feedback.tsx": {
    id: "routes/feedback";
    page: "/feedback";
  };
  "routes/overlay.tsx": {
    id: "routes/overlay";
    page: "/overlay";
  };
  "routes/navigation.tsx": {
    id: "routes/navigation";
    page: "/navigation";
  };
  "routes/commerce.tsx": {
    id: "routes/commerce";
    page: "/commerce";
  };
  "routes/utils.tsx": {
    id: "routes/utils";
    page: "/utils";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/general": typeof import("./app/routes/general.tsx");
  "routes/data-display": typeof import("./app/routes/data-display.tsx");
  "routes/form": typeof import("./app/routes/form.tsx");
  "routes/feedback": typeof import("./app/routes/feedback.tsx");
  "routes/overlay": typeof import("./app/routes/overlay.tsx");
  "routes/navigation": typeof import("./app/routes/navigation.tsx");
  "routes/commerce": typeof import("./app/routes/commerce.tsx");
  "routes/utils": typeof import("./app/routes/utils.tsx");
};